## Код для GitHubActions. Задаём список DNS-серверов, к которым будем обращаться (чем больше - тем лучше). И задаём доменное имя, все ip-адреса которого нам нужно узнать.

name: DNS Lookup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Ежедневный автозапуск задачи

jobs:

  dns-lookup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: DNS Lookup
      run: |
        
        dns_servers=("8.8.8.8" "1.1.1.1" "9.9.9.9" "8.8.4.4") # Вписываем ДНСы. Лучше конечно иметь файлик со списком серверов, но у меня такого нет.
        touch DNSresult.txt # Проверяем что файлик для вывода результата существует, если нет то создаём.

        # Записываем сюда искомый домен или поддомен
        target = "some.example.com"
        
        # Опрашиваем каждый сервер на наличие интересующей нас записи
        for server in "${dns_servers[@]}"; do
          ip=$(nslookup $target $server | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | sort -u)
          if [ -n "$ip" ]; then
            echo "$ip" >> DNSresult.txt
          fi
        done
        
    - name: Commit changes
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add DNSresult.txt
        git commit -m "Обновление DNSresult.txt" -a || echo "No changes to commit"
        git push origin || echo "No changes to push"
